### ISSUE TITLE
当dumpdecrypted -X时报错

### ISSUE THREAD

**Issue by chibofeng** [4ch12dy/xia0LLDB#29]
(lldb) dumpdecrypted -X
[*] set breakpoint at CFBundleGetMainBundle
[*] will continue process and dump
[*] start execute dumpdecrypted
[*] delete all breakpoints
[-] failed to auto get main module, use -m option
[-] failed to auto get main module, use -m option
Traceback (most recent call last):
  File "/Users/XX/xia0LLDB/src/dumpdecrypted.py", line 51, in handle_command
    ret = dumpdecrypted(debugger)
  File "/Users/XX/xia0LLDB/src/dumpdecrypted.py", line 546, in dumpdecrypted
    images = utils.get_all_image_of_app()
  File "/Users/XX/xia0LLDB/src/utils.py", line 121, in get_all_image_of_app
    if app_path.startswith("/private"):
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by JoshuaFeng5** [comment]
同样的报错

**Comment by SjonC** [comment]
解决了吗

**Comment by chibofeng** [comment]
> 解决了吗

没有, 已经放弃了

**Comment by zy364601065** [comment]
有解决这个问题吗
