### ISSUE TITLE
你好。反反调试出现这个错误

### ISSUE THREAD

**Issue by lidonghe0525** [4ch12dy/xia0LLDB#9]
Traceback (most recent call last):
  File "/Users/admin/xia0LLDB/src/debugme.py", line 43, in handle_command
    debugme(debugger)
  File "/Users/admin/xia0LLDB/src/debugme.py", line 718, in debugme
    images = utils.get_all_image_of_app()
  File "/Users/admin/xia0LLDB/src/utils.py", line 102, in get_all_image_of_app
    image_name = image_str.split(",")[1]
IndexError: list index out of range
[x] happy debugging~ kill antiDebug by xia0@2019

**Comment by 4ch12dy** [comment]
在执行debugme前先执行croc命令了吗
